### ISSUE TITLE
Hook is validating all old commits with user slug/email. Not able to push the changes after preforming  local merge from master to branch.

### ISSUE THREAD

**Issue by araviteja** [tomasbjerre/simple-bitbucket-commit-checker#73]
Hi Tomas,

Below is the scenario:
User configured the required git config and able to push changes to remote branch. 

When users performs a local merge from master to his branch, When he try to push changes to remote branch, hook is throwing Error message. Hook is validating the all old commits  which are from master and throwing an error saying that user slug and email is not matching with the committer.Hook is expecting old commits also should have committer as user who is pushing now.  While pushing it is showing conflict for all master commits. 

We have a shared repo where different users will push the changes to master. Hook should not validate the old/history commits which are already part of master. it should validate the new commits which are part of this branch.

Checking all commits in branches is causing issue. we should ignore the old commits which are already part of master.

Can you please check on this. 

Regards,
Raviteja

**Comment by tomasbjerre** [comment]
That should also be fixed in 3.5. what version do you use?

Den 31 juli 2017 08:12 skrev "araviteja" <notifications@github.com>:

**Comment by araviteja** [comment]
Our current version is 3.5. Still facing same. 

Version:
3.5
Vendor:
Tomas Bjerre
Add-on key:
se.bjurr.sscc.sscc

Regards,
Raviteja

**Comment by tomasbjerre** [comment]
Try 3.6, open issue again if not working

**Comment by araviteja** [comment]
Thanks a lot for your quick help.
